### ISSUE TITLE
[Android] Login dialog doesn't accept numbers or backspace

### ISSUE THREAD

**Issue by R2D221** [aritchie/userdialogs#400] opened 2017-07-13 01:22 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [] iOS
 - [x] Android
 - [] UWP
 - [] NET Standard 1.1

## Version of OS(s) listed above with issue

Android 7.0

## Version of ACR UserDialogs Library

6.5.1

## Expected Behaviour

Being able to write numbers or erase mistakes.

## Actual Behavior
_If applicable, please include entire exception - type, message, stacktrace_

Numbers and backspace seemingly do nothing. This issue was reported before and fixed, so I double-checked I had installed all the updates before reporting it again.

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by Im-PJ** [comment] 2018-02-12 05:04
I'm facing the same issue on Android API 16. Username field of Login dialog doesn't accept numbers.

**Comment by deczaloth** [comment] 2018-04-17 12:58
Anything new on this issue?

**Comment by cvasquez-github** [comment] 2018-05-08 18:13
Same issue here! And when trying to update to 7.0.1 via NuGet Packages Manager, we receive the following error message: 

Error Failed to add reference. The package 'Acr.UserDialogs' tried to add a framework reference to 'OpenTK-1.0' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component.			0

**Comment by cvasquez-github** [comment] 2018-05-08 18:47
Same issue here! Same behavior, tested in Android OS 7.0, using Acr.UserDialogs 6.5.1 and 7.0.1.

**Comment by mrbelk** [comment] 2018-10-23 17:32
I have experienced the same problem, using the UserDialogs v7.0.1 on Xamarin Forms 3.3, on Android 5.0.1

**Comment by EmmanVazz** [comment] 2018-12-27 19:06
For anyone that runs into this issue, I just uncommented the OnKeyPress function commented out here and it worked.
https://github.com/aritchie/userdialogs/blob/4836c8e69e96bdb297179f69becf9f5fd245624c/src/Acr.UserDialogs/Platforms/Android/Fragments/LoginDialogFragment.cs#L10

Seems it was commented out to fix (https://github.com/aritchie/userdialogs/issues/302) but that issue isn't happening for me.

**Comment by sawankumarbundelkhandi** [comment] 2019-03-19 14:15
It's not working with Google Keyboard (GBoard) but is working fine with Grammarly keyboard.

**Comment by alexwambre** [comment] 2020-02-19 13:20
Hello.

The issue is still here in 7.0.35. It's impossible to backspace with some keyboards.

**Comment by aritchie** [comment] 2020-02-19 14:11
@alexwambre feel free to send a fix.  I don't use this dialog at all.

**Comment by bares43** [comment] 2020-03-26 19:29
@aritchie It's fixed in #710, can you please check the PR?

**Closed** 2020-03-27 11:43 UTC
Labels: bug, help wanted, pinned
