### ISSUE TITLE
UserDialogs.Instance.ShowError() causes crash on Android 6.0 - API 23

### ISSUE THREAD

**Issue by parkej60** [aritchie/userdialogs#159] opened 2016-05-03 18:35 UTC
1) Please check all of the platforms you are having the issue on
[] Android

2) Please state the issue to the best of your ability below
I'm calling 'UserDialogs.Instance.ShowLoading("Loading")' and then waiting for a response to come back from a webservice. Once I receive the response I either calling 'UserDialogs.Instance.HideLoading()' or 'UserDialogs.Instance.ShowError("Error Logging In")`.

If I have an error and call 'UserDialogs Instance.ShowError("Error Logging In")' I get the below exception. If there is no error it works find and hides the loading mask. This is only happening on Android. Works great on iOS.

3) Please copy and paste the exception details below.  If you are having a crash and this detail is missing, your issue will be closed without warning.

Unhandled Exception:

Android.Views.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class <unknown>

Thank you for your continued support of this library.

**Comment by aritchie** [comment] 2016-05-03 22:10
There is a rather large chunk of that exception missing.  Can you please include the entire stack so that I can get a better idea of what may be going on.

**Comment by aritchie** [comment] 2016-05-06 23:48
I have been unable to reproduce this.  Closing as no additional info has been sent.

**Closed by aritchie** 2016-05-06 23:48 UTC
Labels: more info needed
