### ISSUE TITLE
[Enhancement] AndroidX Support

### ISSUE THREAD

**Issue by bdgza** [aritchie/userdialogs#741] opened 2020-08-19 14:06 UTC
We use AndroidX AppCompat in our Xamarin Forms solution. After updating from AndroidX AppCompat 1.1.0.1 to 1.2.0 the app crashes when Acr.UserDialogs is called on to show an alert.

## Platform

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library

7.1.0.446

## Version of OS(s) listed above with issue

Android 9 (physical Samsung tablet and Emulator), Xamarin Forms 4.8.0.1269
Visual Studio for Mac 8.7.3 (build 13), Mono Framework 6.12.0.90, Xamarin Android 11.0.2.0

## Steps to Reproduce
1. Create new XF Android app
2. Update all NuGets to latest, install Acr.UserDialogs latest, install AndroidX AppCompat 1.2.0
3. Add a button with a call to show AlertAsync()
4. Run app and push the button
(see attached sample project)

## Expected Behavior

The app should show the user dialog alert as requested.

## Actual Behavior

The app crashes with:
> [Mono] Requesting loading reference 3 (of 4) of /storage/emulated/0/Android/data/com.xf.bug.acttest/files/.__override__/AcrTest.dll
> [Mono] Loading reference 3 of /storage/emulated/0/Android/data/com.xf.bug.acttest/files/.__override__/AcrTest.dll asmctx DEFAULT, looking for Acr.UserDialogs, Version=7.1.0.446, Culture=neutral, PublicKeyToken=null
> [Mono] Assembly Ref addref AcrTest[0xec244b80] -> Acr.UserDialogs[0xec2448e0]: 3
> [] * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/metadata/class.c:1845, condition `method->is_inflated' not met
> [libc] Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18842 (.xf.bug.acttest), pid 18842 (.xf.bug.acttest)

[AcrTest.zip](https://github.com/aritchie/userdialogs/files/5096923/AcrTest.zip)

**Comment by aritchie** [comment] 2020-08-19 14:36
You have to use the migration nuget from Xamarin

**Comment by bdgza** [comment] 2020-08-19 14:40
The Migration package is included in our app where we have the problem, version 1.0.6.2.

It was not included in the sample project. After adding it to AcrTest it still crashes the same.

**Comment by aritchie** [comment] 2020-08-19 14:46
I would contact Xamarin first then so they are aware of breaking changes.

**Comment by clnorris** [comment] 2020-08-25 00:19
Google Play Store is warning that existing apps must target API 29, so upgrading all my nuget to AndroidX incl. Xamarin.AndroidX.Migration.  Experiencing the same problem of crash when ConfirmAsync is called.
08-24 18:15:10.785 F/        (14851): * Assertion at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mono/metadata/class.c:1845, condition `method->is_inflated' not met

**Comment by aritchie** [comment] 2020-08-25 01:08
@clnorris You can target API 29 without upgrading to AndroidX.  If you can't wait, send a PR - otherwise the "me toos" are only an annoyance.  I don't have a need to upgrade this library myself right and it isn't two minutes of effort.

**Comment by sarthak1995-26** [comment] 2020-08-25 09:30
I think the issue is because of 👍 Could not resolve reference to 'AndroidX.AppCompat.App.AppCompatDialogFragment' (defined in assembly 'Acr.UserDialogs) You will get this error when trying to build android build in release mode with linker set to SDK assemble only.

Acr.UserDialog version : latest stable
Xamarin.AndroidX.AppCompat : 1.2.0

What I have found is AndroidX.AppCompat.App.AppCompatDialogFragment class is not longer available in 1.2.0(Xamarin.AndroidX.AppCompat) and it's looks like Acr is refrencing this class somewhere

**Comment by sarthak1995-26** [comment] 2020-08-25 09:31
Here's the full error stack

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(5,5): Error XALNK7000: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'AndroidX.AppCompat.App.AppCompatDialogFragment' (defined in assembly 'Acr.UserDialogs, Version=7.1.0.446, Culture=neutral, PublicKeyToken=null') with scope 'Xamarin.AndroidX.AppCompat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve AndroidX.AppCompat.App.AppCompatDialogFragment
  at Mono.Linker.Steps.MarkStep.HandleUnresolvedType (Mono.Cecil.TypeReference reference) [0x00013] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x0002c] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00060] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at MonoDroid.Tuner.MonoDroidMarkStep.MarkType (Mono.Cecil.TypeReference reference) [0x00000] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkGenericParameter (Mono.Cecil.GenericParameter parameter) [0x00034] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkGenericParameterProvider (Mono.Cecil.IGenericParameterProvider provider) [0x0001f] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkEntireType (Mono.Cecil.TypeDefinition type) [0x00096] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkEntireType (Mono.Cecil.TypeDefinition type) [0x0001e] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.MarkEntireAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x0003a] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.InitializeAssembly (Mono.Cecil.AssemblyDefinition assembly) [0x00045] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.Initialize () [0x00014] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Steps.MarkStep.Process (Mono.Linker.LinkContext context) [0x00007] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at MonoDroid.Tuner.MonoDroidMarkStep.Process (Mono.Linker.LinkContext context) [0x0000b] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Pipeline.ProcessStep (Mono.Linker.LinkContext context, Mono.Linker.Steps.IStep step) [0x0000d] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Mono.Linker.Pipeline.Process (Mono.Linker.LinkContext context) [0x0000f] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at MonoDroid.Tuner.Linker.Run (Mono.Linker.Pipeline pipeline, Mono.Linker.LinkContext context) [0x00000] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at MonoDroid.Tuner.Linker.Process (MonoDroid.Tuner.LinkerOptions options, Mono.Linker.ILogger logger, Mono.Linker.LinkContext& context) [0x00071] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x001dd] in <0d3a2268388448fdb90b4a54c411a87d>:0 
   --- End of inner exception stack trace ---
  at Java.Interop.Tools.Diagnostics.Diagnostic.Error (System.Int32 code, System.Exception innerException, System.String message, System.Object[] args) [0x00000] in /Users/builder/azdo/_work/287/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs:166 
  at Xamarin.Android.Tasks.LinkAssemblies.Execute (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver res) [0x00276] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Xamarin.Android.Tasks.LinkAssemblies.RunTask () [0x0001b] in <0d3a2268388448fdb90b4a54c411a87d>:0 
  at Xamarin.Android.Tasks.AndroidTask.Execute () [0x00000] in <0d3a2268388448fdb90b4a54c411a87d>:0  (XALNK7000) (Fraikin.Mobile.Android)

**Comment by bdgza** [comment] 2020-08-25 09:33
https://github.com/xamarin/AndroidX/issues/141

**Comment by sarthak1995-26** [comment] 2020-08-25 13:15
So I believe we have to wait for next AndroidX nuget update

**Comment by clnorris** [comment] 2020-08-25 18:30
@aritchie Thanks for the sage advice, targeting API 29 without the AndroidX migration has eventually worked.  Somehow I had the impression all these changes had to be taken together (was following Microsoft's AndroidX doc).

After changing the targeting, it did complain about some missing AndroidX packages even though I didn't migrate my project, for example it said I was missing Xamarin.AndroidX.MediaRouter.  If I removed the corresponding old package, in this case Xamarin.Android.Support.v7.MediaRouter, then I was able to build and debug ok.  In the debugger, I am seeing a bunch of AndroidX DLL loading up in the background, guess framework is using some of AndroidX even though my project didn't have the AndroidX migration.

Anyway, sorry for the "me too" not meaning to annoy but not sure thru Github how to communicate things like frequency of occurrence and issue severity when multiple folks are blocked.

Will target API 29 for now and save the AndroidX for another day.  Been adopting a few other Acr libs like bluetoothle so will be owing you coffee.

Thx @bdgza and @sarthak1995-26 for the other issue status info.

Cheers, CN

**Comment by dinisvieira** [comment] 2020-08-25 18:44
@clnorris You should be able to use ACR, AndroidX and Target API 29 as long as you don't use the latest 1.2.0 version.
Version 1.1.0.1 is working great for me with ACR and targeting API 29.
It might be a bit of work if you have a lot of AndroidX libs but it should be possible.

In case it's any help these are the versions that I'm using for the AndroidX libs I have:
> Xamarin.AndroidX.AppCompat.Resources 1.1.0.1
> Xamarin.AndroidX.Core 1.2.0.1
> Xamarin.AndroidX.Legacy.Support.Core.Utils 1.0.0.1
> Xamarin.AndroidX.Browser 1.2.0.1
> Xamarin.AndroidX.ExifInterface 1.1.0.1
> Xamarin.AndroidX.Lifecycle.LiveData 2.2.0.1
> Xamarin.AndroidX.AppCompat 1.1.0.1
> Xamarin.AndroidX.Legacy.Support.V4 1.0.0.1
> Xamarin.AndroidX.CardView 1.0.0.1
> Xamarin.AndroidX.MediaRouter 1.1.0.1
> Xamarin.AndroidX.Migration 1.0.6.1

**Comment by Jakar510** [comment] 2020-09-01 20:26
I'm having this issue as well.

**Comment by aritchie** [comment] 2020-09-01 20:42
@Jakar510 this has already been answered above.  Your “me too” without any info or actual effort in contributing is just useless noise.

**Comment by CleverSoftwarePoland** [comment] 2020-09-02 11:49
I have the same problem with latest Xamarin.AndroidX libs. 

This line can narrow the problem to a missing class reference "AndroidX.AppCompat.App.AppCompatDialogFragment"
var frag = (ConfirmAppCompatDialogFragment)Activator.CreateInstance(ConfirmAppCompatDialogFragment);

Problem starts with nuget "Xamarin.AndroidX.AppCompat" version 1.2.0 if you go back to 1.1.0.2 it works.

**Comment by sarthak1995-26** [comment] 2020-09-04 06:13
We use AndroidX AppCompat in our Xamarin Forms solution. After updating from AndroidX AppCompat 1.1.0.1 to 1.2.0 the app crashes when Acr.UserDialogs is called on to show an alert.

This error fixed with Xamarin.AndroidX.AppCompact version 1.2.0.2

**Comment by BacClunky** [comment] 2020-09-10 08:59
Hey guys,

Again, following my steps to avoid these issues,
To me, Android project version is 9 -> Upgrade to 10 -> Die

1. Go to .nuget\packages folder and delete all the folders xamarin.androidx.*
2. So, please make your Android project goes back to version 9, open nuget and update all the AndroidX to latest version
3. Rebuild solution again. It builds successfully

Hope this help,

**Closed** 2020-09-10 09:00 UTC
Labels: enhancement, help wanted
