### ISSUE TITLE
Build Failed while compiling UWP in Xamarin.Forms Project

### ISSUE THREAD

**Issue by Femilshajin** [aritchie/userdialogs#112] opened 2016-01-05 06:03 UTC
Hi, When I add the acr.userdialogs to the UWP Project and compile it the error below shows up. I'm using Acr.Userdialogs 4.2.0

Severity	Code	Description	Project	File	Line
Error		Could not copy the file "C:\Users\<UserName>\.nuget\packages\Acr.UserDialogs\4.2.0\lib\uap10.0\Acr.UserDialogs\Acr.UserDialogs.xr.xml" because it was not found.

**Comment by ValdimarThor** [comment] 2016-01-05 10:51
Having the same problem here. Would be nice to see a fix for this as soon as posible :)

**Comment by aritchie** [comment] 2016-01-08 13:36
Does 4.2.1 on nuget resolve the issue for you?

**Comment by Femilshajin** [comment] 2016-01-08 14:10
Sorry, No Still unable to copy the file Acr.UserDialogs.xr.xml but the file was there in the specified destination.

**Comment by ValdimarThor** [comment] 2016-01-08 14:11
No such luck for me I'm afraid :( 
still get "Error		Payload file 'C:\Users\myuser\.nuget\packages\Acr.UserDialogs\4.2.1\lib\uap10.0\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist.
One thing to note: My UWP project references Xamarin Forms PCL project, so should'nt the reference to Acr come from the portable-win+net45+wp8+win8+wpa81 folder instead of uap10.0?

**Comment by aritchie** [comment] 2016-01-08 17:10
Please confirm it says Acr.UserDialogs.xd.xml and not Acr.UserDialogs.xr.xml (it should have the XD portion, not xr)

**Comment by Femilshajin** [comment] 2016-01-11 09:10
It is Acr.UserDialogs.xr.xml Manually copying it under Acr.UserDialogs Folder works for me.

**Comment by wcoder** [comment] 2016-01-18 10:21
Hi, I using version 4.2.1.

The same error:
```
Payload file 'C:\Users\wcoder\.nuget\packages\Acr.UserDialogs\4.2.1\lib\uap10.0\Acr.UserDialogs\Acr.UserDialogs.xr.xml' does not exist.
```

**Comment by wcoder** [comment] 2016-01-18 10:24
@Femilshajin, thanks!
Your hack is working!

But, I thing it is not good.

Someone has bug, maybe in Nuget?

**Comment by tvoth** [comment] 2016-02-04 18:21
@aritchie this issue still exists.  I can confirm that is is the Acr.UserDialogs.xr.xml and NOT Acr.UserDialogs.xd.xml as you say it should be.

I installed the package using Visual Studio's "Package Manage Console" and the command Install-Package Acr.UserDialogs.  After running that command, I do not have a `'C:\Users\<name>\.nuget\packages\Acr.UserDialogs\4.2.1\lib\uap10.0\Acr.UserDialogs\'` folder in my system; but once I create on and copy the Acr.UserDialogs.xr.xml from `'C:\Users\<name>\.nuget\packages\Acr.UserDialogs\4.2.1\lib\uap10.0'` into it; the compiling works fine.

**Comment by aritchie** [comment] 2016-02-28 18:34
I am having a hell of a time causing this issue.  All compiles work for me on past versions.  I have released an update to remove any trace of the xr.xml inside the nuget packages which is what they recommend for this XD files as well.

Please give it a try and send feedback if good please

**Comment by aritchie** [comment] 2016-02-28 18:44
I lied.  I actually made sure it includes the Xr.xml in the proper folder.  Hopefully this solves things

**Comment by cleardemon** [comment] 2016-03-02 16:32
4.3.4 seems to have fixed UWP for me.

**Comment by aritchie** [comment] 2016-03-02 19:30
@cleardemon Thanks for the update.  Anyone else?

**Comment by EmilAlipiev** [comment] 2016-03-06 22:21
It doesnt work for me. I cant initiliaze it. no instance. how to get an instance? I am able to run same code in XF on android

**Comment by gmwilhelm** [comment] 2016-03-18 06:55
Works for me, too

**Comment by pafvcio** [comment] 2016-04-12 08:49
When will be resolved bug with ShowLoading on WP 8.1 (XAML parsing failed)?

**Comment by aritchie** [comment] 2016-04-12 10:38
Probably never.  I'm not getting any help with wp81 and the platform is absolutely useless to me to invest any time in to.

Please don't ask about timelines in the future!  If you want support for something in the future, why not make a PR to help out.

**Closed** 2016-04-16 17:19 UTC
Labels: bug, more info needed

**Comment by tvoth** [comment] 2016-05-12 15:25
@aritchie, sorry for the (very) late update but we we stuck in an unrelated issue updating our systems.  Now that we have, your fix has worked wonderfully.  Thank you.

**Comment by johnm01** [comment] 2017-03-23 15:14
I have the problem resurrected in  March 2017 - beta version 2.4.0.65 -beta

Payload file 'C:\Users\john\.nuget\packages\Xam.Plugin.Connectivity\2.4.0.65-beta\lib\UAP10\Plugin.Connectivity\Properties\Plugin.Connectivity.rd.xml' does not exist.	nGar10k.UWP			

going back to the stable version just for the UWP project gets around it 
trouble is that the nuget install on the latest version does not create any deeper folders that UAP10 so the ..UAP10\Plugin.Connectivityand subfolders and files just dont exist

**Comment by aritchie** [comment] 2017-03-23 15:16
@johnm01 I think you have the wrong project

**Comment by johnm01** [comment] 2017-03-23 15:22
Ahh yes - but the symptoms arevery similar- Thought  I was commenting on Plugin.Connectivity thread
thanks anyway

**Comment by Clement-Jean** [comment] 2019-02-26 08:20
I have the same issue but for 7.0.3 release...
