### ISSUE TITLE
Prompt is not showing on iOS

### ISSUE THREAD

**Issue by LSMadsen** [aritchie/userdialogs#380] opened 2017-05-17 06:50 UTC
# IF YOU DO NOT USE THIS TEMPLATE - YOUR ISSUE WILL BE CLOSED.  PLEASE READ THE FAQ AND THE CODE OF CONDUCT BELOW!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [X] iOS
 - [] Android
 - [] UWP
 - [] PCL

## Version of OS(s) listed above with issue
iOS version 10.3.1

## Version of ACR UserDialogs Library
6.4.1

## Expected Behaviour
I expected the PromptDialog to show up with the decimal keyboard

## Actual Behavior
Only the decimal keyboard shows up, and the user has to close the app to close the keyboard.

I am using this code to show the Prompt dialog

```
UserDialogs.Instance.PromptAsync(new PromptConfig
{
   Title = "Add materials",
   Message = "Enter the amount of materials to add",
   OkText = "OK",
   CancelText = "Cancel",
   InputType = InputType.DecimalNumber,
   IsCancellable = true,
});
```

## Code of Conduct
* No Library Update Requests
* No Timeline Requests
* Please read through the documentation and FAQs
* Please be respectful of my time. I put a lot of effort into my libraries.  I try to support the issue requests within a day.  I'm not psychic, so please take the time to fill out the above form as complete as possible

**Comment by aritchie** [comment] 2017-05-17 09:50
It works fine in the sample.  Can you please attach a reproducible sample

**Comment by aritchie** [comment] 2017-05-20 23:36
No follow up provided.  Closing issue

**Closed by aritchie** 2017-05-20 23:36 UTC
Labels: more info needed

**Comment by LSMadsen** [comment] 2017-05-22 06:13
Sorry, I have been ill since my question 
The problem occurs on iOS 10.3.1

I get this Exception
Can't find keyplane that supports type 8 for keyboard iPhone-Portrait-DecimalPad; using 405786210_Portrait_iPhone-Simple-Pad_Default

**Comment by LSMadsen** [comment] 2017-05-22 09:39
I figured out, the problem was, that before displaying the Prompt I showed an ActionSheet. And without a delay, this error occured.

**Comment by CalvinFong** [comment] 2017-06-18 14:21
Just ran into this bug. To clarify for anyone else. The issue is as follows.

This will NOT work:
var answer = await App.Current.MainPage.DisplayActionSheet ("Title","okay",null,"a","b","c");
if (answer == "a"){
        Acr.UserDialogs.PromptConfig alert = new Acr.UserDialogs.PromptConfig { Title="t", Message="m" };
	PromptResult prmt = await UserDialogs.Instance.PromptAsync (alert);
	if (prmt.Ok == true) {  // do stuff    }
}

This WILL work:
await App.Current.MainPage.DisplayActionSheet ("Title","okay",null,"a","b","c")
	 .ContinueWith (async x => {
	 	  var answer = x.Result;
	 	  if (answer == "a"){
        	  	  Acr.UserDialogs.PromptConfig alert = new Acr.UserDialogs.PromptConfig { Title="t", Message="m" };
		 	  PromptResult prmt = await UserDialogs.Instance.PromptAsync (alert);
		 	  if (prmt.Ok == true) {  // do stuff    }
	 	 }
});

**Comment by aritchie** [comment] 2017-06-18 23:09
Just add a delay of 100ms between showing two dialogs.  This is a bigger problem on android.  Or don't show two dialogs back to back, the end user experience is horrible

**Comment by nmdias** [comment] 2017-07-17 09:26
Yup, the delay fixed it for me too. I was showing an Action Sheet before calling the Prompt.

Thanks
