### ISSUE TITLE
[Bug] OnCreateDialog crashes

### ISSUE THREAD

**Issue by SOFSPEEL** [aritchie/userdialogs#637] opened 2019-07-29 18:48 UTC
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ x] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library
7.0.4

## Version of OS(s) listed above with issue
Android 7, 8, 9

## Steps to Reproduce
Not sure how to reproduce, however our Android crash reporting (AppCenter) is reporting a high incidence (around 30 instances for different users and going up daily) of the following crash:
```
ConfigStore.Pop[T] (Android.OS.Bundle bundle)
System.Collections.Generic.KeyNotFoundException: The given key '1' was not present in the dictionary.
Dictionary`2[TKey,TValue].get_Item (TKey key)
ConfigStore.Pop[T] (Android.OS.Bundle bundle)
AbstractAppCompatDialogFragment`1[T].OnCreateDialog (Android.OS.Bundle bundle)
DialogFragment.n_OnCreateDialog_Landroid_os_Bundle_ (System.IntPtr jnienv, System.IntPtr native__this, System.IntPtr native_savedInstanceState)
```
![image](https://user-images.githubusercontent.com/1612646/62072733-155c0700-b1f4-11e9-8e9a-74a5d000695f.png)

Looking at the code in https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs/Platforms/Android/Fragments/AbstractDialogFragment.cs, looks like about 2 years ago there was some mitigation effort to try to prevent this type of exception by doing a !ConfigStore.Instance.Contains(bundle) check.

I'm speculating that possibly a threading issue remains as follows:

In
https://github.com/aritchie/userdialogs/blob/master/src/Acr.UserDialogs/Platforms/Android/Fragments/ConfigStore.cs

the Store method is:

```
 public void Store(Bundle bundle, object config)
        {
 line 1          this.counter++;
 line 2         this.configStore[this.counter] = config;
 line 3         bundle.PutLong(this.BundleKey, this.counter);
        }
```
ConfigStore is a singleton, so **counter** is a singleton, so if multiple threads call Store simultaneously then its possible to store the wrong counter in the dictionary/bundle. To overcome this issue some type of locking/interlock can be placed on the counter in the store method.

Note that to try to repro this issue, I've tried quickly hitting button multiple times in succession that trigger dialogs i.e. so as to get as many OnCreateDialogs as possible, but so far no luck.

## Expected Behavior
No crash.

## Actual Behavior
Crashes

**Comment by aritchie** [comment] 2019-07-29 19:00
Please add some sort of test case as you figure them out.  I don't want to take shots in the dark at this.

**Comment by aritchie** [comment] 2019-08-22 11:58
No test case has been supplied.

**Comment by ElteHupkes** [comment] 2019-09-17 15:43
I just want to add to this that we have also been experiencing this issue for a while. Unfortunately I haven't been able to reproduce it. Judging from the `OnCreateDialog` code,

```
public override Dialog OnCreateDialog(Bundle bundle)
        {
            Dialog dialog = null;
            if (this.Config == null && !ConfigStore.Instance.Contains(bundle))
            {
                this.ShowsDialog = false;
                this.Dismiss();
            }
            else
            {
                this.Config = this.Config ?? ConfigStore.Instance.Pop<T>(bundle);
                dialog = this.CreateDialog(this.Config);
                this.SetDialogDefaults(dialog);
            }
            return dialog;
        }
```

it _must_ be a race condition. In order for this to happen `this.Config` has to be `null` and `ConfigStore.Instance.Contains(bundle)` has to be true - however once `ConfigStore.Instance.Pop<T>(bundle)` is called the item is no longer present in the store, meaning something removed it. I'm not sure how that can even happen even if duplicate IDs are handed out, because unless I misunderstand this functionality it would also require multiple dialogs to be open...

@aritchie I'd like to help with this in any case you can, but I highly doubt anybody will be able to create a reliable test case for this, as it seems to require getting the app backgrounded in a particular way. I'm a bit puzzled because I always thought `OnSaveInstanceState` runs on the main thread. I'll see if I can find out something more.

**Comment by ElteHupkes** [comment] 2019-09-17 15:58
Actually, now that I read through the code more carefully, I figured it should be possible to reproduce this bug using tombstoning, and indeed I can. Repro:

- Open a dialog
- Switch to the home screen
- Flood your memory with something like Android Toolbelt (opening the camera may suffice on some devices too). This will cause Android to kill open apps to get more memory.
- Once the memory jumps back up, the app has likely been killed in the background. Switch back to your app with the open dialog using the task switcher.
- Crash!

This happens because ConfigStore.Instance.Contains(bundle) only checks if the bundle contains the key with the identifier. It then takes the identifier from that bundle and tries to take it from the dictionary. That dictionary however is empty at this point, because the entire app (that includes the ConfigStore) has been removed from memory.

@aritchie Can you reopen this issue?

**Comment by ElteHupkes** [comment] 2019-09-18 08:17
The solution for this really kind of depends on how thoroughly we'd like this case to be handled. There are two options:

1. We're okay with the dialog closing when the app is restored from persisted state. That's a bit sloppy but the fix is probably a couple of lines of code at most.
2. The dialog needs to be restored from state fully. I honestly don't know if this is even possible without making big changes to the API, because it requires the entire configuration objects to be serializable to simple types and actually perform that serialization. Anything with an `Action` or similar is out, async calls would break too.

So I'm thinking probably 1, which essentially keeps the current behavior except it would close the dialog gracefully instead of crashing the entire app. I can create a PR later today.

**Comment by ElteHupkes** [comment] 2019-09-19 08:12
@aritchie Thanks for the swift action and great work in general. This one can be closed I think.

**Closed** 2019-09-20 00:34 UTC
Labels: bug, pinned, unverified
