### ISSUE TITLE
Linking issue with System.Drawing.Color

### ISSUE THREAD

**Issue by dynamisoft** [aritchie/userdialogs#656] opened 2019-08-23 03:12 UTC
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [ X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Feature Library

 - [X ] Core
 - [ ] BluetoothLE
 - [ ] Locations
 - [ ] HTTP Transfers
 - [ ] Notifications
 - [ ] Sensors

## Version of Library 
Just downloaded 7.0.26, previously using 7.0.25

## Version of OS(s) listed above with issue
KitKat - 4.4.  This is an Android only issue

## Steps to Reproduce
1. Compile the application with Use Shared runtime off
2. Use the "Sdk Assemblies Only" Linking Option
3. Click Deploy.

## Expected Behavior
The application runs fine, this linking issue recently showed up with no changes.  When I saw your latest update was trying to resolve a mapping issue with this I thought this would be it.  Any help is appreciated.

## Actual Behavior
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Drawing.Color' (defined in assembly 'Acr.UserDialogs, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null') with scope 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Drawing.Color

**Comment by dynamisoft** [comment] 2019-08-23 03:22
Sorry, when I meant the "application runs fine" i meant it runs on emulators.  As soon as I try to deploy it to the device is when this linking error appears.  I have tried with both 4.4 and 8.1 devices.

It was previously running fine even on the device, this is a recent phenom.  I traced back to anything recently installed and there were only a couple minor things that are both back to their original versions.

**Comment by HelenMamalaki** [comment] 2019-08-23 10:29
I got everything working fine in my project testing on a physical Android 9 device in debug mode but just discovered you get this build error in release mode. The plugin is useless if it cannot build in release mode??
Can see issue in v7.0.25 and 7.0.26 (using NetStandard shared code Xamarin.Forms project.)

**Comment by aritchie** [comment] 2019-08-23 11:40
@HelenMamalaki Comments like these are rude and completely unnecessary.  It doesn't add any value or additional information to helping solve the issue.  This isn't a paid product and it also isn't my problem you're "blocked".  You aren't blocked - you can go back to a previous version like v7.0.4 which is fine.  This bug is with Xamarin/Microsoft who I am working with to get this resolved.

**Comment by HelenMamalaki** [comment] 2019-08-23 14:08
@aritchie I didn't mean to come off as rude :( I was only trying to call attention to the issue in the hopes that it be acknowledged soon. The new information in my comment (not included by original author) is that I only see the issue in Release mode, and it works fine on a physical device in debug mode for me. 
I can build the app with v7.0.4 in release mode which is great, so thank you for the a way forward!

**Comment by dynamisoft** [comment] 2019-08-23 14:31
Aritchie/Helen,
thanks for the information.  We spent a few very long days on this not knowing if we had done something wrong or there was a real problem.  Just knowing this is an issue and having a way forward helps a lot.  Thanks!

**Comment by dynamisoft** [comment] 2019-08-23 14:38
when you say you can rebuild the app in v7.0.4 do you mean v7.0.24 or is there another library we are missing?

**Comment by HelenMamalaki** [comment] 2019-08-23 14:47
v7.0.4 is the version just before 7.0.22 - see version history [here](https://www.nuget.org/packages/Acr.UserDialogs) I can see it in NuGet Package Manager too. ;)

**Comment by dynamisoft** [comment] 2019-08-23 14:51
thanks Helen, much appreciated!  Was able to compile with link options, huge help!  I will sit tight on 7.0.26 until MS gets this resolved.  Is there a bug from Xamarin/Microsoft tracking what they broke?

**Comment by Andrew-Bekhiet** [comment] 2019-08-26 11:44
I've also the same issue :(

**Comment by aritchie** [comment] 2019-08-26 11:46
Closing this as a dupe of #654

**Closed by aritchie** 2019-08-26 11:46 UTC
