### ISSUE TITLE
[Bug] java.lang.RuntimeException: Unable to start activity ComponentInfo {UserDialogs} does not have a Dialog.

### ISSUE THREAD

**Issue by JMan7777** [aritchie/userdialogs#759] opened 2020-11-12 12:56 UTC
## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ ] iOS
 - [X] Android
 - [ ] UWP
 - [ ] .NET Standard

## Version of Library

7.1.0.466

Using also the following Xamarin.AndroidX packages:

```
    <PackageReference Include="Xamarin.AndroidX.Annotation">
      <Version>1.1.0.7</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Arch.Core.Common">
      <Version>2.1.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Arch.Core.Runtime">
      <Version>2.1.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Collection">
      <Version>1.1.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Concurrent.Futures">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout">
      <Version>2.0.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout.Solver">
      <Version>2.0.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.CoordinatorLayout">
      <Version>1.1.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI">
      <Version>1.0.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.DrawerLayout">
      <Version>1.1.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ExifInterface">
      <Version>1.3.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.5.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.Extensions">
      <Version>2.2.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Media">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.PercentLayout">
      <Version>1.0.0.6</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.SlidingPaneLayout">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Transition">
      <Version>1.3.1.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat">
      <Version>1.2.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.CardView">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.GridLayout">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.2.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Palette">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Preference">
      <Version>1.1.1.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.RecyclerView">
      <Version>1.1.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.VectorDrawable">
      <Version>1.1.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.VersionedParcelable">
      <Version>1.1.1.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ViewPager">
      <Version>1.0.0.5</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Annotation">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.AppCompat.Resources">
      <Version>1.1.0.1</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ConstraintLayout">
      <Version>1.1.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.ExifInterface">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Fragment">
      <Version>1.2.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.GridLayout">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.UI">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.V4">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Lifecycle.LiveData">
      <Version>2.2.0.3</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.MediaRouter">
      <Version>1.1.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Migration">
      <Version>1.0.8</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.PercentLayout">
      <Version>1.0.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.AndroidX.Preference">
      <Version>1.1.1</Version>
```

## Version of OS(s) listed above with issue

"model": "Pixel 2",
"oemName": "Google",
"osName": "Android",
"osVersion": "8.1.0",
"osBuild": "OPM1.180608.001",
"osApiLevel": 27

## Steps to Reproduce

We are getting a rare error in our production Xamarin Android app which crashes and we cannot reproduce/identify the problem.
(We don't have that physical device available for testing/debugging)

The error mentioned below only happens on one specific device so far but we cannot pinpoint the route cause.
(The app is built for Android 6 - 11)

Right after our main activties OnCreate method finishes the crash happens.
(We first have a splash activity which then starts the main activity)
The stack trace below is all we have and we assume it's related to your package as it mentions `UserDialogs`.

We would appreciate if you could give us an idea if this could be something related to your code.

Thx a lot. 

## Expected Behavior

No error.

## Actual Behavior

```
"stackTrace": "
  --- End of managed Java.Lang.RuntimeException stack trace ---
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.MyApp/crc64ea6ca85821d5349c.MainActivity}: java.lang.IllegalStateException: DialogFragment ConfirmAppCompatDialogFragment{3b4c435} (7d57e355-dead-4965-9878-3157089685a6) UserDialogs} does not have a Dialog.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.IllegalStateException: DialogFragment ConfirmAppCompatDialogFragment{3b4c435} (7d57e355-dead-4965-9878-3157089685a6) UserDialogs} does not have a Dialog.
	at androidx.fragment.app.DialogFragment.requireDialog(DialogFragment.java:302)
	at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:425)
	at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1485)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2637)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1334)
	at android.app.Activity.performStart(Activity.java:7029)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2741)
	... 9 more
",
```

**Comment by aritchie** [comment] 2020-11-12 13:09
It looks like you're closing the activity at the same time you are opening a dialog.  Hard to tell from the exception.  I really need code with some sort of reproducible case in order to figure it out.

**Comment by JMan7777** [comment] 2020-11-12 14:52
Thx a million for the hint. I was suspecting something like that and I think I found the cause in our code.

**Closed** 2020-11-12 14:52 UTC
